#cloud-config

users:
  - name: skydns
    system: true
coreos:
  update:
    reboot-strategy: etcd-lock
  etcd:
    discovery: https://discovery.etcd.io/<token>
    addr: `wget -qO- http://instance-data/latest/meta-data/local-ipv4`:4001
    peer-addr: `wget -qO- http://instance-data/latest/meta-data/local-ipv4`:7001
  fleet:
    public-ip: wget -qO- http://instance-data/latest/meta-data/public-ipv4
    metadata: region=us-west-2,instance-type=m3.medium
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: skydns.installer.service
      command: start
      content: |
        [Unit]
        Description=SkyDNS Installer

        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=-/usr/bin/mkdir -p /var/lib/skydns/bin
        ExecStart=-/usr/bin/wget --no-check-certificate -O /var/lib/skydns/bin/skydns https://s3-us-west-2.amazonaws.com/coreos-beta/skydns
        ExecStart=/usr/bin/chown skydns:skydns /var/lib/skydns/bin/skydns
        ExecStart=/usr/bin/chmod +x /var/lib/skydns/bin/skydns
    - name: skydns.service
      command: start
      content: |
        [Unit]
        Description=skydns
        Requires=skydns.installer.service
        Requires=etcd.service
        Requires=docker.service
        After=skydns.installer.service
        After=etcd.service
        After=docker.service

        [Service]
        User=skydns
        Group=skydns
        Type=simple
        # see: http://coreos.com/blog/docker-dynamic-ambassador-powered-by-etcd/#toc_4
        # "172.17.42.1:4001 is the known address for etcd on every CoreOS instance from inside of a Docker container"
        ExecStart=/var/lib/skydns/bin/skydns -addr 172.17.42.1 -verbose=true -discover=true

        PermissionsStartOnly=true
        # ExecStartPre=/usr/sbin/sysctl -w net.ipv4.ip_forward=1
        ExecStartPre=-/sbin/iptables -D INPUT -p udp --dport 5333 -j ACCEPT
        ExecStartPre=-/sbin/iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5333
        ExecStartPre=/sbin/iptables -A INPUT -p udp --dport 5333 -j ACCEPT
        ExecStartPre=/sbin/iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5333
        ExecStopPost=/sbin/iptables -D INPUT -p udp --dport 5333 -j ACCEPT
        ExecStopPost=/sbin/iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5333

        Restart=always
        RestartSec=5
        # WorkingDirectory=/tmp
        # PrivateTmp=true
        # NoNewPrivileges=true
        ReadOnlyDirectories=/etc

        [Install]
        WantedBy=multi-user.target
